### ISSUE TITLE
Getting tracking info of (yet) unused tracking number fails validation

### ISSUE THREAD

**Issue by Cyberuben** [goshippo/shippo-javascript-sdk#18]
Hi,

I'm attempting to get the tracking info of several parcels, and I know a lot of them might not have been used yet, or will never be used. Currently, I'm getting the following error tracking these parcels:

```json
{
    "name": "SDKValidationError",
    "cause": {
        "issues": [
            {
                "code": "invalid_type",
                "expected": "string",
                "received": "undefined",
                "path": [
                    "tracking_history",
                    0,
                    "status_date"
                ],
                "message": "Required"
            }
        ],
        "name": "ZodError"
    },
    "rawValue": {
        "tracking_number": "<REDACTED>",
        "carrier": "ups",
        "servicelevel": {},
        "transaction": "<REDACTED>",
        "address_from": {
            "city": "<REDACTED>",
            "state": "<REDACTED>",
            "zip": "<REDACTED>",
            "country": "US"
        },
        "address_to": {
            "city": "<REDACTED>",
            "state": "<REDACTED>",
            "zip": "<REDACTED>",
            "country": "US"
        },
        "test": false,
        "tracking_history": [
            {
                "status_details": "Pre-Transit: Shipment information has been transmitted to the shipping carrier but it has not yet been scanned and picked up.",
                "object_created": "2024-05-06T11:37:39.842Z",
                "object_updated": "2024-05-06T11:37:39.842Z",
                "object_id": "<REDACTED>",
                "status": "UNKNOWN"
            }
        ],
        "messages": []
    }
}
```

The tracking history clearly mentions Pre-Transit, but the status there is `UNKNOWN`, that seems quite conflicted to me. This seems like either something that has to be fixed in the API response, or something that has to be fixed in the validation, because this seems like a perfectly valid state in tracking.

**Comment by shippo-lueders** [comment]
[status_date](https://docs.goshippo.com/shippoapi/public-api/#operation/CreateTrack!c=201&path=tracking_history/status_date&t=response) is required according to our API specification.  I'm checking with the team whether this is actually the case.

**Comment by shippo-lueders** [comment]
I've confirmed this is a bug and is actively being worked, I'll close this ticket once the fix has been released.

**Comment by Cyberuben** [comment]
Thanks for the quick responses the last few days!

**Comment by shippo-lueders** [comment]
quick update - this has been fixed but it doesn't look like it made yesterday's cutoff, should go out on Monday

**Comment by Cyberuben** [comment]
Any news on the fix yet? I'm still getting the same amount of API errors

**Comment by shippo-lueders** [comment]
I'm trying to track that down... I see the fix was merged but don't see it in the deployment logs, will update this ticket with an ETA later today

**Comment by shippo-lueders** [comment]
looks like it will be going out today, still not sure why it didn't go yesterday

**Comment by Cyberuben** [comment]
Sadly I'm still getting the same errors

**Comment by shippo-lueders** [comment]
apparently it isn't all the way fixed... I'm just going to update the client to not require status_date, at least until this issue gets resolved.  you'll still get the `status_details` "Pre-Transit: Shipment..." and `status` "UNKNOWN" until the underlying issue is actually resolved, but at least the calls won't explode.  I'll update this ticket once the fix is published.

**Comment by shippo-lueders** [comment]
https://www.npmjs.com/package/shippo/v/2.2.5 will fix the validation error you're getting.

I expect the tracking status fix to go out early next week, feel free to re-open if you're still getting wonky results

**Comment by shippo-lueders** [comment]
actually, something went wrong with publication, that package I linked was published two days ago, investigating

**Comment by shippo-lueders** [comment]
https://www.npmjs.com/package/shippo/v/2.2.6
